

name: spend-tracker

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - spend-tracker

  api:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./Server/.env
    volumes:
      - ./Server:/app
      - /app/node_modules
    ports:
      - "8081:8080"
    depends_on:
      - mongo
    networks:
      - spend-tracker

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - api
    networks:
      - spend-tracker

volumes:
  mongo_data:

networks:
  spend-tracker:
    driver: bridge
